# BUILD redislabs/rmbuilder:x64-buster

ARG OSNICK=buster

#---------------------------------------------------------------------------------------------- 
FROM redis:5.0.5 AS redis

#---------------------------------------------------------------------------------------------- 
FROM debian:buster

COPY --from=redis /usr/local /usr/local

WORKDIR /rmbuilder

# Set up a build environment
COPY deps/ deps/
COPY system-setup.py .

RUN ./deps/readies/bin/getpy2
RUN ./system-setup.py 

WORKDIR /builder

RUN rm -rf /rmbuilder

ENV LIBDIR /usr/lib/redis/modules
